package com.neueda.interview.urlshortener.service;

import com.neueda.interview.urlshortener.repository.UrlRepository;
import com.neueda.interview.urlshortener.common.ShorteningUtil;
import com.neueda.interview.urlshortener.model.UrlEntity;
import com.neueda.interview.urlshortener.dto.FullUrl;
import com.neueda.interview.urlshortener.dto.ShortUrl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.NoSuchElementException;

import com.neueda.interview.urlshortener.model.User;

@Service
public class UrlService {

    Logger logger = LoggerFactory.getLogger(UrlService.class);

    private final UrlRepository urlRepository;

    // 用户相关方法
    public List<UrlEntity> findByUser(User user) {
        return urlRepository.findByUser(user);
    }

    public UrlEntity createShortUrl(String fullUrl, String customSuffix, User user) {
        UrlEntity urlEntity = new UrlEntity();
        urlEntity.setFullUrl(fullUrl);
        urlEntity.setUser(user);
        if (customSuffix != null && !customSuffix.isEmpty()) {
            urlEntity.setShortUrl(customSuffix);
        }
        UrlEntity saved = urlRepository.save(urlEntity);
        if (customSuffix == null || customSuffix.isEmpty()) {
            String shortUrlText = ShorteningUtil.idToStr(saved.getId());
            saved.setShortUrl(shortUrlText);
            saved = urlRepository.save(saved);
        }
        return saved;
    }

    public void deleteUrl(Long id) {
        urlRepository.deleteById(id);
    }

    public UrlEntity editUrl(Long id, String newFullUrl) {
        UrlEntity urlEntity = urlRepository.findById(id).orElseThrow(() -> new RuntimeException("Not found"));
        urlEntity.setFullUrl(newFullUrl);
        return urlRepository.save(urlEntity);
    }

    @Autowired
    public UrlService(UrlRepository urlRepository) {
        this.urlRepository = urlRepository;
    }

    private UrlEntity get(Long id) {
        logger.info(String.format("Fetching Url from database for Id %d", id));
        UrlEntity urlEntity = urlRepository.findById(id).get();
        return urlEntity;
    }

    public UrlEntity getByShortUrl(String shortUrl) {
        return urlRepository.findByShortUrl(shortUrl)
                .orElseThrow(() -> new NoSuchElementException("Url not found"));
    }

    /**
     * Uses the Base62 encoded to convert to Base10 number and fetches the corresponding record from the database
     *
     * @param shortenString Base62 encoded string
     * @return FullUrl object
     */
    public FullUrl getFullUrl(String shortenString) {
        logger.info(String.format("Retrieving full url for %s", shortenString));
        UrlEntity urlEntity = urlRepository.findByShortUrl(shortenString)
                .orElseThrow(() -> new NoSuchElementException("Url not found"));
        return new FullUrl(urlEntity.getFullUrl());
    }

    private UrlEntity save(FullUrl fullUrl) {
        return urlRepository.save(new UrlEntity(fullUrl.getFullUrl()));
    }

    /**
     * It saves the full url to database and uses the autogenerated id to convert to Base62 string
     *
     * @param fullUrl FullUrl object to be converted to shortened url
     * @return ShortUrl object
     */
    public ShortUrl getShortUrl(FullUrl fullUrl) {

        logger.info("Checking if the url already exists");
        List<UrlEntity> savedUrls = null;
        savedUrls = checkFullUrlAlreadyExists(fullUrl);

        UrlEntity savedUrl = null;

        if (savedUrls.isEmpty()) {
            logger.info(String.format("Saving Url %s to database", fullUrl.getFullUrl()));
            savedUrl = this.save(fullUrl);
            logger.debug(savedUrl.toString());
        }
        else {
            savedUrl = savedUrls.get(0);
            logger.info(String.format("url: %s already exists in the database. skipped insert", savedUrl));
        }

        logger.debug(String.format("Converting Base 10 %d to Base 62 string", savedUrl.getId()));
        String shortUrlText = ShorteningUtil.idToStr(savedUrl.getId());
        logger.info(String.format("Converted Base 10 %d to Base 62 string %s", savedUrl.getId(), shortUrlText));

        return new ShortUrl(shortUrlText);
    }

    /**
     * Check if Url already exists in the database to prevent having same url stored multiple times
     *
     * @param fullUrl
     * @return list of UrlEntity objects, list will be empty if no results found
     */
    private List<UrlEntity> checkFullUrlAlreadyExists(FullUrl fullUrl) {
        return urlRepository.findUrlByFullUrl(fullUrl.getFullUrl());
    }
}
